# Generated by Django 4.2.16 on 2024-12-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0086_issueversion_alter_teampage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='props',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
