# Generated by Django 4.2.16 on 2024-12-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0087_issue_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Admin'), (15, 'Member'), (14, 'Writer'), (13, 'SE'), (12, 'VOA'), (5, 'Guest')], default=5),
        ),
        migrations.AlterField(
            model_name='projectmemberinvite',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Admin'), (15, 'Member'), (14, 'Writer'), (13, 'SE'), (12, 'VOA'), (5, 'Guest')], default=5),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Admin'), (15, 'Member'), (14, 'Writer'), (13, 'SE'), (12, 'VOA'), (5, 'Guest')], default=5),
        ),
        migrations.AlterField(
            model_name='workspacememberinvite',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Admin'), (15, 'Member'), (14, 'Writer'), (13, 'SE'), (12, 'VOA'), (5, 'Guest')], default=5),
        ),
    ]
